fest: TimelineTabs can scroll by mouse wheel without pressing shift.
RSSNext/Follow pull request #1081
Opened 2024-10-23 12:55 UTC by xhuajin

### Description

**new feature**

TimelineTabs can scroll by mouse wheel without pressing shift. 

gif-demo: https://github.com/user-attachments/assets/e544d4e7-41b3-400c-a130-ad83614ef865

![gif-demo](https://github.com/user-attachments/assets/e544d4e7-41b3-400c-a130-ad83614ef865)

**fix**

Titles in timelinetabs cannot be displayed completely because of line-height:1.

img: https://github.com/user-attachments/assets/6dd6f1a2-dcf6-46af-81b4-8d9082436b04

![image-demo](https://github.com/user-attachments/assets/6dd6f1a2-dcf6-46af-81b4-8d9082436b04)

2024-10-23 15:23 UTC, hyoban requested changes

2024-10-23 15:23 UTC, hyoban commented on apps/renderer/src/modules/entry-column/layouts/TimelineTabs.tsx
> +  })
Why register event listeners during rendering?

2024-10-23 15:26 UTC, xhuajin commented on apps/renderer/src/modules/entry-column/layouts/TimelineTabs.tsx
> +  })
因为 timelineTabs 中的内容排列方向是 flex-direction: row，tab 如果太多的话，多余的部分会隐藏。想要看到后面的tab的内容需要按住 shift 再滚动。监听这里的滚动事件可以直接滚动查看溢出的 tab

2024-10-23 16:03 UTC, Innei requested changes

2024-10-23 16:03 UTC, Innei commented on apps/renderer/src/modules/entry-column/layouts/TimelineTabs.tsx
> +  })
You need to follow the React philosophy, writing it this way can lead to memory leaks

2024-10-23 16:24 UTC, xhuajin commented on apps/renderer/src/modules/entry-column/layouts/TimelineTabs.tsx
> +  })
Thanks for telling me, I used onWheel() to add the listener instead

2024-10-24 00:48 UTC, hyoban commented
/ai-review

2024-10-24 00:50 UTC, hyoban commented
Thanks for your contribution!

2024-10-24 00:50 UTC, merged