Update zh-CN.json
RSSNext/Follow pull request #1344
Opened 2024-11-03 02:49 UTC by inblossoms

Synchronize translation information to Chinese.

### Description

### PR Type

- [ ] Feature
- [ ] Bugfix
- [ ] Hotfix
- [x] Other (please describe):

### Additional context

2024-11-03 05:12 UTC, xuanxuan1231 commented
Repeated pull request #1296

2024-11-03 09:15 UTC, Innei requested changes

2024-11-03 09:15 UTC, Innei commented on locales/settings/zh-CN.json
> +  "appearance.custom_css.description": "自定义上下文中的 css 样式",
```suggestion
  "appearance.custom_css.description": "自定义条目渲染中的 CSS 样式",
```

2024-11-03 09:15 UTC, Innei commented on locales/settings/zh-CN.json
> +  "appearance.thumbnail_ratio.description": "文章缩略图在列表中的比例",
```suggestion
  "appearance.thumbnail_ratio.description": "列表中文章缩略图的比例",
```

2024-11-04 06:47 UTC, Innei approved these changes
Thank you for your contribution.

2024-11-04 06:48 UTC, merged