feat: mobile app
RSSNext/Follow pull request #2144
Opened 2024-12-13 11:11 UTC by hyoban

### Description

### PR Type

- [ ] Feature
- [ ] Bugfix
- [ ] Hotfix
- [ ] Other (please describe):

### Linked Issues

### Additional context

### Changelog

- [ ] I have updated the changelog/next.md with my changes.

2024-12-16 19:17 UTC, lawvs commented on vite.config.ts
> +    base: "./",
@Innei Does it work for the web build?

2024-12-17 07:51 UTC, Innei commented on vite.config.ts
> +    base: "./",
It works.

2024-12-17 10:50 UTC, Innei requested changes

2024-12-17 10:50 UTC, Innei commented on apps/mobile/src/components/common/FollowWebView.tsx
> -  window.__RN__ = true
Need this @hyoban

2024-12-25 16:06 UTC, merged