chore(i18n): added tw support
RSSNext/Follow pull request #398
Opened 2024-09-14 09:03 UTC by gcaaa31928

### Description

### Linked Issues

### Additional context

2024-09-14 11:18 UTC, TonyRL commented on locales/settings/en.json
> -  "about.changelog": "Changelog",
This is the English localisation file which shouldn't be changed.

2024-09-14 11:23 UTC, gcaaa31928 commented on locales/settings/en.json
> -  "about.changelog": "Changelog",
you are right, thanks

2024-09-14 11:52 UTC, gcaaa31928 commented
@TonyRL  @Innei  please review it, thanks !!

2024-09-14 12:02 UTC, Innei requested changes

2024-09-14 12:02 UTC, Innei commented on locales/app/zh-TW.json
> +  "entry_list.zero_unread": "Zero Unread",
Missed

2024-09-14 12:02 UTC, Innei commented on locales/app/zh-TW.json
> +  "tip_modal.tip_support": "⭐ Tip to show your support!",
and

2024-09-14 12:02 UTC, Innei commented on locales/app/zh-TW.json
> +  "sync_indicator.disabled": "Due to security reasons, sync is disabled.",
and

2024-09-14 12:03 UTC, Innei commented
plz review self first.

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "ai_daily.tooltip.content": "以下是 AI 從您的時間軸中選擇的新聞 (<From /> - <To />)，可能對您很重要。",
```suggestion
  "ai_daily.tooltip.content": "以下是 AI 從您的時間軸中選擇的新聞（<From /> - <To />），可能對您很重要。",
```

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "entry_content.fetching_content": "正在獲取原始內容並處理...",
```suggestion
  "entry_content.fetching_content": "正在獲取原始內容並處理……",
```

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "feed_claim_modal.rsshub_notice": "此摘要由 RSSHub 提供，快取時間為 1 小時。發布內容後，請最多等待 1 小時以顯示變更。",
```suggestion
  "feed_claim_modal.rsshub_notice": "此摘要由 RSSHub 提供，快取時間為 1 小時。發佈內容後，請最多等待 1 小時以顯示變更。",
```

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "feed_item.error_since": "Error since",
Missing translation

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "search.placeholder": "搜尋...",
```suggestion
  "search.placeholder": "搜尋……",
```

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "sidebar.feed_actions.open_feed_in_browser": "使用瀏覽器打開 Feed",
Missing translations of `feed` to `摘要`

2024-09-14 13:16 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "tip_modal.unclaimed_feed": "目前尚無人認領此 Feed。收到的 Power 將安全地保存在區塊鏈合約中，直到被認領為止。",
same as above

2024-09-14 13:16 UTC, TonyRL commented on locales/external/zh-TW.json
> +    "earlyAccessMessage": "😰 抱歉，追蹤目前處於搶先體驗階段，需要邀請碼才能使用。",
```suggestion
    "earlyAccess": "Follow 目前處於搶先體驗階段，需要邀請碼才能使用。",
    "earlyAccessMessage": "😰 抱歉，Follow 目前處於搶先體驗階段，需要邀請碼才能使用。",
```

2024-09-14 13:16 UTC, TonyRL commented on locales/settings/zh-TW.json
> +  "actions.action_card.enable_readability": "啟用可讀性",
```suggestion
  "actions.action_card.enable_readability": "啟用閱讀模式",
```
Firefox call their readability `閱讀模式`
https://support.mozilla.org/zh-TW/kb/firefox-reader-view-clutter-free-web-pages

2024-09-14 13:16 UTC, TonyRL commented on locales/settings/zh-TW.json
> +  "appearance.content_font": "Content Font",
Missing translations

2024-09-14 13:16 UTC, TonyRL commented on locales/shortcuts/zh-TW.json
> +  "keys.audio.playPause": "播放/暫停（當音頻播放器開啟時）",
```suggestion
  "keys.audio.playPause": "播放／暫停（當音頻播放器開啟時）",
```

2024-09-14 14:45 UTC, TonyRL commented on locales/app/zh-TW.json
> +  "discover.default_option": " (預設) ",
https://github.com/RSSNext/Follow/pull/398#discussion_r1759732893
This is a fullwidth punctuation `（` instead of a halfwidth ` (` with a space

2024-09-14 15:08 UTC, gcaaa31928 commented on locales/app/zh-TW.json
> +  "discover.default_option": " (預設) ",
Done~

2024-09-14 16:31 UTC, TonyRL approved these changes

2024-09-14 16:31 UTC, TonyRL commented on locales/settings/zh-TW.json
> +  "wallet.withdraw.success": "送出成功！"
```suggestion
  "wallet.withdraw.success": "提取成功！"
```
https://github.com/RSSNext/Follow/blob/e1233a3f008abaf0dc4102d9d20777e77f27f1c7/locales/settings/en.json#L194

2024-09-14 17:02 UTC, TonyRL approved these changes

2024-09-15 02:23 UTC, gcaaa31928 commented
It seems everything is fine now. Thank you both for carefully reviewing it. Please help me merge this request.

2024-09-15 05:22 UTC, Innei approved these changes

2024-09-15 05:22 UTC, merged

2024-09-15 05:22 UTC, Innei commented
Thank you!