feat(i18n): add Spanish language support
RSSNext/Follow pull request #400
Opened 2024-09-14 09:38 UTC by upupnoah

Added Spanish translations to the application, including localization for app content, common phrases, external resources, language settings, and shortcuts.

### Description

### Linked Issues

### Additional context

2024-09-14 10:00 UTC, Innei requested changes

2024-09-14 10:00 UTC, Innei commented on locales/lang/es.json
> +  "langs.zh-CN": "简体中文",
You should add `langs.es` in every `lang/*.json`

2024-09-14 10:02 UTC, upupnoah commented on locales/lang/es.json
> +  "langs.zh-CN": "简体中文",
okey

2024-09-14 10:12 UTC, upupnoah commented on locales/lang/es.json
> +  "langs.zh-CN": "简体中文",
> You should add `langs.es` in every `lang/*.json`

Already added.

2024-09-16 07:02 UTC, Innei commented
Please resolves conflicts

2024-09-16 07:56 UTC, upupnoah commented
> Please resolves conflicts
Conflict has been resolved.

2024-09-16 07:57 UTC, upupnoah commented
> Please resolves conflicts

Conflict has been resolved.

2024-09-16 10:46 UTC, Innei approved these changes

2024-09-16 10:47 UTC, Innei commented
Thank you!

2024-09-16 10:47 UTC, merged