Add Dutch Language Support
RSSNext/Follow pull request #446
Opened 2024-09-16 14:19 UTC by brandon-qq

Added Dutch translations to the application, including localization for app content, common phrases, external resources, language settings, and shortcuts.

### Description

### Linked Issues

### Additional context

2024-09-20 07:59 UTC, hyoban commented
Please do not change package.json and remove package-lock.json

2024-09-20 09:55 UTC, Innei requested changes

2024-09-20 09:55 UTC, Innei commented on package-lock.json
No lock file

2024-09-20 09:55 UTC, Innei commented on package.json
> +    "pnpm": "^9.10.0",
no pnpm

2024-09-20 09:55 UTC, Innei commented on src/renderer/src/modules/discover/DiscoverFeedForm.tsx
> +        {renderedPath.trim()} {/* Ensure rendered path is trimmed */}
You don't have to do something over and over again.

2024-09-20 10:09 UTC, brandon-qq commented on package-lock.json
What do you mean with this?

2024-09-20 10:09 UTC, brandon-qq commented on package.json
> +    "pnpm": "^9.10.0",
Is Follow not built on pnpm? Why not use pnpm then

2024-09-28 03:42 UTC, Innei commented
@brandon-qq Hi, could you resolve the conflicts? thx

2024-09-28 21:01 UTC, brandon-qq commented
![image](https://github.com/user-attachments/assets/64ea5c0c-353f-4553-bea9-f09ddb517f49)
Literally cannot...? @Innei

2024-10-23 10:58 UTC, Innei commented
I am closing this PR due to a long period of time without resolving the conflict. Thank you for your time.

2024-10-23 10:58 UTC, closed without merging