feat: add more words i18n
RSSNext/Follow pull request #516
Opened 2024-09-19 18:39 UTC by jerryc127

### Description

### Linked Issues

### Additional context

2024-09-20 00:45 UTC, Innei requested changes

2024-09-20 00:45 UTC, Innei commented on apps/renderer/src/hooks/biz/useSubscriptionActions.tsx
> +                <Trans ns="app" i18nKey="words.undo" />
```suggestion
                {t('words.undo')}
                
```

2024-09-20 00:45 UTC, Innei commented on apps/renderer/src/modules/discover/import.tsx
> -    title: "Parsed Error Items",
use `I18nKeys` to define `title`

2024-09-20 03:51 UTC, jerryc127 commented
@Innei Done

2024-09-20 11:18 UTC, Innei requested changes

2024-09-21 12:04 UTC, jerryc127 commented on apps/renderer/src/modules/entry-content/index.tsx
> -              <a
因爲我看到 app 裏面 語言文件 有個 entry_content.web_app_notice，參數存在，但是 follow 沒有使用過這個參數，看這個命名，跟這個是差不多意思的，所以就刪掉，用 語言文件那個 `<span>{t("entry_content.web_app_notice")}</span>`

```
  "entry_content.web_app_notice": "Maybe web app doesn't support this content type. But you can download the desktop app.",
```

2024-09-21 12:06 UTC, jerryc127 commented on apps/renderer/src/modules/discover/import.tsx
>                    <div className={cn("mb-4 text-lg font-medium", item.className)}>{item.title}</div>
前面的 list 的 title，已經用 Trans 獲取翻譯的值，爲什麽這裏又要 {t(item.title)}？

2024-09-21 13:23 UTC, Innei commented on apps/renderer/src/modules/discover/import.tsx
>                    <div className={cn("mb-4 text-lg font-medium", item.className)}>{item.title}</div>
这里不需要用 <Trans />

2024-09-21 17:51 UTC, jerryc127 commented on apps/renderer/src/modules/discover/import.tsx
>                    <div className={cn("mb-4 text-lg font-medium", item.className)}>{item.title}</div>
好的 那就是不用修改

2024-09-22 08:56 UTC, jerryc127 commented on apps/renderer/src/modules/entry-content/index.tsx
> -              <a
@Innei please review

2024-09-22 10:15 UTC, Innei reviewed
LGTM

2024-09-22 12:01 UTC, Innei approved these changes

2024-09-22 12:39 UTC, jerryc127 commented
这是在干嘛，一直推送？

2024-09-22 13:05 UTC, merged

2024-09-22 13:05 UTC, jerryc127 commented
@Innei 这是在干嘛