feat(i18n): add de
RSSNext/Follow pull request #538
Opened 2024-09-20 19:52 UTC by upupnoah

### Description

### Linked Issues

### Additional context

2024-09-21 04:40 UTC, Innei requested changes

2024-09-21 04:40 UTC, Innei commented on locales/external/en.json
> -  "header.app": "App",
Why change its structure?

2024-09-21 11:00 UTC, upupnoah commented on locales/external/en.json
> -  "header.app": "App",
> Why change its structure?

I'm a bit confused. Logically, the keys in a JSON file within a directory should be the same, so why are there some that start with copy_link and others that start with feed?

2024-09-24 04:22 UTC, Innei commented
@upupnoah Could you take some time to solve the conflicts?

2024-09-24 10:41 UTC, upupnoah commented
> @upupnoah Can you spare some time to resolve the conflicts?

Conflict has been resolved

2024-09-25 02:15 UTC, Innei commented
@upupnoah CI's reporting an error, can you fix it?

2024-09-25 07:05 UTC, upupnoah commented
> @upupnoah CI's reporting an error, can you fix it?

It has been fixed now.

2024-09-25 09:34 UTC, Innei requested changes

2024-09-25 09:34 UTC, Innei commented on apps/renderer/src/@types/constants.ts
> +  "de",
Moving down, `en` needs to be first

2024-09-25 17:57 UTC, upupnoah commented on apps/renderer/src/@types/constants.ts
> +  "de",
okey

2024-09-26 09:16 UTC, Innei approved these changes
Thank you

2024-09-26 09:16 UTC, merged