feat: add some i18n
RSSNext/Follow pull request #616
Opened 2024-09-24 16:27 UTC by ischanx

### Description

![image](https://github.com/user-attachments/assets/dfaf0a04-d8f4-4bab-a92e-d278d4d37f8f)
![image](https://github.com/user-attachments/assets/66391007-68ff-4409-8dfe-0bda67974d4c)

### Linked Issues

### Additional context

2024-09-25 13:00 UTC, Innei requested changes

2024-09-25 13:00 UTC, Innei commented on apps/renderer/src/constants/shortcuts.ts
> +export const shortcutsType: { [key in keyof typeof shortcuts]: string } = {
```suggestion
export const shortcutsType: { [key in keyof typeof shortcuts]: I18nKeys } = {
```

2024-09-25 13:28 UTC, ischanx commented on apps/renderer/src/constants/shortcuts.ts
> +export const shortcutsType: { [key in keyof typeof shortcuts]: string } = {
Thanks for your review, but type I18nKeys can not be used, i add a new type I18nKeysForShortcuts

2024-09-26 09:18 UTC, Innei approved these changes

2024-09-26 09:18 UTC, Innei commented
Thank you

2024-09-26 09:18 UTC, merged