fix: grid mode for images and video content page, shadow not fully displayed when the mouse hovers over the image
RSSNext/Follow pull request #710
Opened 2024-09-29 06:57 UTC by cuikaipeng

In the grid browsing mode of images and on the video content display page, when the mouse hovers over an image, the shadow is not fully displayed and appears truncated at the top.
I identified that the issue was caused by the "inset-y-1" style in the 「ListItemHoverOverlay」 component.
As this is a foundational component, I opted not to modify it directly. Instead, I introduced an "overlayItemClassName" attribute to the 「EntryItemWrapper」 component to address the style issue.
<img width="929" alt="iShot_2024-09-29_13 45 17" src="https://github.com/user-attachments/assets/05c65a3f-67e3-4ff7-a577-1423ce5a6b06">

2024-09-29 09:10 UTC, Innei requested changes

2024-09-29 09:10 UTC, Innei commented on apps/renderer/src/modules/entry-column/item.tsx
> +      Item.overlayItemClassName = "top-0"
Don't change the Item's properties here, you should add them when the Item component is defined.

2024-09-29 09:51 UTC, cuikaipeng commented on apps/renderer/src/modules/entry-column/item.tsx
> +      Item.overlayItemClassName = "top-0"
oh, sorry, I don't know how to 「add them when the Item component is defined」
I defined a variable to set the "overlayItemClassName" property of 「EntryItemWrapper」
Is this ok?
<img width="1097" alt="iShot_2024-09-29_17 45 41" src="https://github.com/user-attachments/assets/7fff3bdf-4bcf-4210-966c-3c8bb4f20c77">

2024-09-30 09:05 UTC, closed without merging

2024-09-30 09:08 UTC, cuikaipeng commented
I noticed a commit by the manager that refactored the component I had modified, so I closed this PR.