fix: media preview bug when zero size, close #764
RSSNext/Follow pull request #765
Opened 2024-10-05 12:23 UTC by cesaryuan

### Description

Close #764

### Linked Issues

#764

### Additional context

2024-10-05 14:29 UTC, Innei requested changes

2024-10-05 14:29 UTC, Innei commented on apps/renderer/src/components/ui/media/preview-media.tsx
> +            height * width === 0
If height or width got `Nan` there will got some issue, `NaN * NaN !== 0`

2024-10-06 02:01 UTC, cesaryuan commented on apps/renderer/src/components/ui/media/preview-media.tsx
> +            height * width === 0
done

2024-10-06 13:07 UTC, Innei commented on apps/renderer/src/components/ui/media/preview-media.tsx
> +                  ...props.style,
```suggestion
      props.style
```

2024-10-07 12:17 UTC, Innei commented
/ai-reviewer

2024-10-07 12:18 UTC, Innei commented
/ai-review

2024-10-07 12:21 UTC, Innei approved these changes

2024-10-07 12:25 UTC, Innei approved these changes

2024-10-07 12:25 UTC, merged