refactor: make resizing more natural
RSSNext/Follow pull request #771
Opened 2024-10-05 17:42 UTC by xc2

### Description

Resizing is not that natural now.

For example, when we move the top handle, the box becomes shorter from bottom.

https://github.com/user-attachments/assets/bda13586-200b-4809-a070-3ea179bf91a7

This PR combines `resizing` and `dragging` when the user is `resizing` from `top` or `left` to make sure the box is resizing following the cursor. Screencast:

https://github.com/user-attachments/assets/4d9c15b9-52c0-46e6-a9c7-918d5a9dd9e1

### Linked Issues

### Additional context

2024-10-06 06:33 UTC, Innei requested changes

2024-10-06 06:33 UTC, Innei commented on apps/renderer/src/components/ui/modal/stacked/modal.tsx
> +                  drag={draggable && (preferDragDir || draggable)}
```suggestion
                  drag={draggable && preferDragDir}
```

2024-10-06 06:33 UTC, Innei commented on apps/renderer/src/modules/settings/modal/layout.tsx
> +        drag={draggable && (preferDragDir || draggable)}
```suggestion
        drag={draggable && preferDragDir}
```

2024-10-06 13:44 UTC, xc2 commented on apps/renderer/src/modules/settings/modal/layout.tsx
> +        drag={draggable && (preferDragDir || draggable)}
it's in case of `draggable` is `"x"` or `"y"`.

`preferDragDir` is only available on resizing, when resizing is over, `preferDragDir` will be back to `null`.

So `draggable && (preferDragDir || draggable)` here means when the box is draggable, the direction is `preferDragDir` or value of `draggable`

2024-10-07 12:31 UTC, Innei commented
/ai-review

2024-10-07 12:49 UTC, merged