feat: support use default browser open source content
RSSNext/Follow pull request #884
Opened 2024-10-11 13:57 UTC by BlackHole1

### Description

Support adding an option in the settings page to allow users to choose whether to open the original content through the default browser.

### Linked Issues

### Additional context

Close: https://discord.com/channels/1243823539426033696/1294094455485366312

2024-10-11 15:26 UTC, Innei requested changes

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/atoms/settings/general.ts
> +  "useDefaultBrowserOpenSourceContent",
Remove this, This item can be sync to server

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/atoms/settings/general.ts
> +  useDefaultBrowserOpenSourceContent: false,
Move to bottom, This item should not be categorized as an App

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +  const useDefaultBrowserOpenSourceContent = useGeneralSettingKey(
There is no need to observe to this setting item.

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +  const useDefaultBrowserOpenSourceContent = useGeneralSettingKey(
Remove this code

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +          if (useDefaultBrowserOpenSourceContent) {
```suggestion
          if (getGeneralSettings().useDefaultBrowserOpenSourceContent) {
```

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +    useDefaultBrowserOpenSourceContent,
Remove this code

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/modules/settings/tabs/general.tsx
> +  const saveSourceContentSetting = useCallback((checked: boolean) => {
This `useCallback` is unnecessary, remove this wrap or just write function inline

2024-10-11 15:26 UTC, Innei commented on apps/renderer/src/atoms/settings/general.ts
> +  useDefaultBrowserOpenSourceContent: false,
And this name is too lang

2024-10-12 01:42 UTC, BlackHole1 commented on apps/renderer/src/atoms/settings/general.ts
> +  useDefaultBrowserOpenSourceContent: false,
> Move to bottom, This item should not be categorized as an App

Which category do you recommend placing it in? Perhaps we should add a new category? Such as _interaction_ or _misc_.

> And this name is too long.

What do you think of `openContentInBrowser`?

2024-10-12 04:34 UTC, Innei commented on apps/renderer/src/modules/settings/tabs/general.tsx
> +            disabled: !tipcClient,
Remove this

2024-10-12 04:35 UTC, Innei requested changes

2024-10-12 04:35 UTC, Innei commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +          if (useDefaultBrowserOpenSourceContent) {
The logic here is incorrect. You need to make a choice with `openInBrowser` above

2024-10-12 05:14 UTC, BlackHole1 commented
> You need to make a choice with openInBrowser above

I don't quite understand the meaning of this sentence.

BTW. I think this feature might not be suitable, because currently, users can click the article's title or double-click the item to open the browser. 

There are already two entry points provided to the users, so there's no need to add another one.

Therefore, I will close this PR. If anyone has different opinions, feel free to comment :)

2024-10-12 05:14 UTC, closed without merging