增加导出到Obsidian功能
RSSNext/Follow pull request #998
Opened 2024-10-17 10:14 UTC by zjnbwxq

### Description

这个 PR 增加了将内容导出到 Obsidian 的功能，并扩展了语言支持。具体更改包括：

1. 在设置界面添加 Obsidian 集成选项：
   - 添加启用/禁用 Obsidian 导出功能的开关
   - 添加设置 Obsidian vault 路径的选项

2. 为部分语言添加了 Obsidian 相关设置的本地化翻译
   - ar-DZ
   - ar-IQ
   - ar-KW
   - de
   - en
   - es
   - zh-CH
   - zh-HK
   - zh-TW

### Linked Issues

### Additional context

Obsidian 集成功能可以提供了更多的数据管理和笔记整理选择

ObsidianVault路径填入说明：
- Windows: `C:\Users\YourUsername\Documents\ObsidianVault`
- macOS: `/Users/YourUsername/Documents/ObsidianVault`
- Linux: `/home/YourUsername/Documents/ObsidianVault`

#### 如何找到Obsidian Vault路径

1. 打开 Obsidian 应用程序
2. 点击左下角的设置
3. 在设置面板中，选择"关于"选项卡
4. 在"存储库"部分，可以看到"存储库路径"
5. 如果要保存到特定的文件夹，应该在路径后加上文件夹名

请特别关注：
1. Obsidian 集成的实现方式是否合理
2. 新添加的设置选项是否在所有支持的语言中都清晰易懂

2024-10-17 23:50 UTC, hyoban requested changes

2024-10-17 23:50 UTC, hyoban commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +            await tipcClient?.saveToObsidian({
`saveToObsidian` is not implemented

2024-10-18 04:47 UTC, hyoban commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +  // 检查 Obsidian 功能是否启用
请移除中文注释

2024-10-18 04:54 UTC, zjnbwxq commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +  // 检查 Obsidian 功能是否启用
okay.

2024-10-18 06:18 UTC, jerryc127 commented on locales/settings/es.json
> +  "integration.readwise.enable.description": "Mostrar el bot��n 'Guardar en Readwise' cuando esté disponible.",
bot��n ?

2024-10-18 06:18 UTC, jerryc127 commented on locales/settings/zh-HK.json
> +  "wallet.transactions.amount": "數���",
數���?

2024-10-18 09:02 UTC, hyoban requested changes

2024-10-18 09:02 UTC, hyoban commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +  })
We don't need `useQuery` here

2024-10-18 09:14 UTC, zjnbwxq commented on apps/renderer/src/hooks/biz/useEntryActions.tsx
> +  })
what's about `useMutation` ?

2024-10-21 02:52 UTC, merged

2024-10-21 02:53 UTC, hyoban commented
Thanks for your contribution!!